### ISSUE TITLE
Forum Graph 

### ISSUE THREAD

**Issue by deraadt** [ctchanandy/moodle-report_forumgraph#3]
Hi.

I was testing out this report. With Moodle 3.0.2 there are a few problems.

- The graph itself does not draw. I note that someone else has reported that. I'm not sure if some package needs to be install alongside the plugin.
- The capability has the wrong context level, so it works at the site level, but is not viewable within courses. It should be CONTEXT_COURSE or there should be two capabilities, one for course and one for site.
- The controls for selecting a forum are not working properly. The first time you visit the report from a course page, it does allow you to select a forum. There is a know problem noted in the README.txt file and the plugin description and perhaps that is the problem I am experiencing. You can work around this, but still the graph doesn't show.

**Comment by ctchanandy** [comment]
Except for the problem of the graph doesn't show (which I could not recreate using Chrome, the other 2 problems should be fixed (hopefully).
